<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.2" />
		<PackageReference Include="MediatR" Version="11.1.0" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="9.0.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.2">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Swashbuckle.AspNetCore" Version="7.3.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Hms.Application\Hms.Application.csproj" />
		<ProjectReference Include="..\Hms.Domain\Hms.Domain.csproj" />
		<ProjectReference Include="..\Hms.Identity\Hms.Identity.csproj" />
		<ProjectReference Include="..\Hms.Infrastructure\Hms.Infrastructure.csproj" />
		<ProjectReference Include="..\Hms.Persistence\Hms.Persistence.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Controllers\BookingInfos\" />
	  <Folder Include="Controllers\Common\" />
	  <Folder Include="Controllers\EmployeeInfos\" />
	  <Folder Include="Controllers\HotelInfos\" />
	  <Folder Include="Controllers\OrganogramSetup\" />
	  <Folder Include="Controllers\PaymentInfos\" />
	  <Folder Include="Controllers\RoomInfos\" />
	  <Folder Include="Controllers\UserManage\" />
	</ItemGroup>

</Project>
