<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<Folder Include="DTOs\BasicSetup\" />
		<Folder Include="DTOs\BookingInfos\" />
		<Folder Include="DTOs\EmployeeInfos\" />
		<Folder Include="DTOs\GuestInfos\" />
		<Folder Include="DTOs\HotelInfos\" />
		<Folder Include="DTOs\OrganogramSetup\" />
		<Folder Include="DTOs\PaymentInfos\" />
		<Folder Include="DTOs\RoomInfos\" />
		<Folder Include="Enum\" />
		<Folder Include="Features\Common\Handlers\Commands\" />
		<Folder Include="Features\Common\Handlers\Queries\" />
		<Folder Include="Features\Common\Requests\Commands\" />
		<Folder Include="Features\Common\Requests\Queries\" />
		<Folder Include="Features\UserManage\" />
		<Folder Include="Features\BasicSetup\" />
		<Folder Include="Features\BookingInfos\" />
		<Folder Include="Features\EmployeeInfos\" />
		<Folder Include="Features\GuestInfos\" />
		<Folder Include="Features\HotelInfos\" />
		<Folder Include="Features\OrganogramSetup\" />
		<Folder Include="Features\PaymentInfos\" />
		<Folder Include="Features\RoomInfos\" />
		<Folder Include="Helpers\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
		<PackageReference Include="CsvHelper" Version="33.0.1" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
		<PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.3.0" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.2" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.7" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Hms.Domain\Hms.Domain.csproj" />
		<ProjectReference Include="..\Hms.Infrastructure\Hms.Infrastructure.csproj" />
		<ProjectReference Include="..\Hms.Shared\Hms.Shared.csproj" />
	</ItemGroup>

</Project>
