<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>


	<ItemGroup>
		<PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="11.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.2" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Hms.Application\Hms.Application.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Configurations\GuestInfos\" />
	  <Folder Include="Configurations\HotelInfos\" />
	  <Folder Include="Configurations\OrganogramSetup\" />
	  <Folder Include="Configurations\PaymentInfos\" />
	  <Folder Include="Configurations\RoomInfos\" />
	  <Folder Include="Configurations\UserManage\" />
	</ItemGroup>

</Project>
